version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus : '1'
          memory: '2048M'
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    restart: on-failure
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - ES_SERVER_URLS=http://es:9200
    depends_on:
      - es
    restart: on-failure
  nginx:
    image: beevelop/nginx-basic-auth
    ports:
      - "80:80"
    environment:
      # username: admin password: admin
      # genereate your username/password in https://www.web2generators.com/apache-tools/htpasswd-generator
      # DON'T forget to escape any $ with $$
      - HTPASSWD=admin:$$apr1$$2v6to0h8$$lyJ/5eX57mbdNlnAE9Oi/0
      - FORWARD_PORT=16686
      - FORWARD_HOST=jaeger
    depends_on:
      - jaeger

volumes:
  es-data:
